[tox]
envlist =
    py{310,311,312,313,314}-dj52
    py{312,313,314}-dj60
    py{312,313,314}-dj61
skipsdist = True

[testenv]
deps =
    dj52: Django>=5.2,<6.0
    dj60: Django>=6.0,<6.1
    dj61: Django>=6.1,<6.2

    # Django 6.1 support is only on DRF's main branch so far
    !dj61: djangorestframework
    dj61: djangorestframework @ https://github.com/encode/django-rest-framework/archive/main.zip

    openpyxl
    Pillow

    pytest
    pytest-django
    pytest-cov
    django-coverage-plugin
    time-machine

commands = {posargs:python -m pytest}
